package com.xzit.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: tb_account
 */
@Data
public class Account extends AccountKey implements Serializable {
    /**
     * 用户的id
     *
     * Table:     tb_account
     * Column:    users_id
     * Nullable:  false
     */
    private String usersId;

    /**
     * 登录的账号
     *
     * Table:     tb_account
     * Column:    login_account
     * Nullable:  false
     */
    private String loginAccount;

    /**
     * 账号的类别(1:昵称2:手机号3:邮箱)
     *
     * Table:     tb_account
     * Column:    category
     * Nullable:  false
     */
    private String category;

    /**
     * 修改时间
     *
     * Table:     tb_account
     * Column:    edited_time
     * Nullable:  true
     */
    private Date editedTime;

    /**
     * 修改人的id
     *
     * Table:     tb_account
     * Column:    editor
     * Nullable:  true
     */
    private String editor;

    /**
     * 逻辑删除:0=未删除,1=已删除
     *
     * Table:     tb_account
     * Column:    is_deleted
     * Nullable:  true
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_account
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}