package com.xzit.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

@Data
public class AccountKey implements Serializable {
    /**
     * 账号的id
     *
     * Table:     tb_account
     * Column:    id
     * Nullable:  false
     */
    private String id;

    /**
     * 创建时间
     *
     * Table:     tb_account
     * Column:    created_time
     * Nullable:  false
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_account
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}