package com.xzit.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: tb_department
 */
@Data
public class Department implements Serializable {
    /**
     * 科室ID,自增
     *
     * Table:     tb_department
     * Column:    id
     * Nullable:  false
     */
    private String id;

    /**
     * 科室名称
     *
     * Table:     tb_department
     * Column:    dept_name
     * Nullable:  true
     */
    private String deptName;

    /**
     * 备注
     *
     * Table:     tb_department
     * Column:    memo
     * Nullable:  true
     */
    private String memo;

    /**
     * 创建时间
     *
     * Table:     tb_department
     * Column:    create_time
     * Nullable:  true
     */
    private Date createTime;

    /**
     * 创建人
     *
     * Table:     tb_department
     * Column:    creator
     * Nullable:  false
     */
    private String creator;

    /**
     * 最后修改时间
     *
     * Table:     tb_department
     * Column:    edited_time
     * Nullable:  true
     */
    private Date editedTime;

    /**
     * 最后修改人
     *
     * Table:     tb_department
     * Column:    editor
     * Nullable:  false
     */
    private String editor;

    /**
     * 系统状态
     *
     * Table:     tb_department
     * Column:    is_deleted
     * Nullable:  false
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_department
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}