package com.xzit.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: tb_dept_hos
 */
@Data
public class DeptHos implements Serializable {
    /**
     * 主键
     *
     * Table:     tb_dept_hos
     * Column:    id
     * Nullable:  false
     */
    private String id;

    /**
     * 科室ID
     *
     * Table:     tb_dept_hos
     * Column:    dept_id
     * Nullable:  false
     */
    private String deptId;

    /**
     * 医馆ID
     *
     * Table:     tb_dept_hos
     * Column:    hos_id
     * Nullable:  false
     */
    private String hosId;

    /**
     * Table:     tb_dept_hos
     * Column:    create_time
     * Nullable:  true
     */
    private Date createTime;

    /**
     * Table:     tb_dept_hos
     * Column:    edited_time
     * Nullable:  true
     */
    private Date editedTime;

    /**
     * Table:     tb_dept_hos
     * Column:    is_deleted
     * Nullable:  true
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_dept_hos
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}