package com.xzit.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;

/**
 * Table: tb_doctor
 */
@Data
public class Doctor implements Serializable {
    /**
     * 医师ID,自增
     *
     * Table:     tb_doctor
     * Column:    id
     * Nullable:  false
     */
    private String id;

    /**
     * 用户id
     *
     * Table:     tb_doctor
     * Column:    userId
     * Nullable:  true
     */
    private String userid;

    /**
     * 职称
     *
     * Table:     tb_doctor
     * Column:    doc_title
     * Nullable:  true
     */
    private String docTitle;

    /**
     * 医师类型(1-医师、2-助理)
     *
     * Table:     tb_doctor
     * Column:    doc_type
     * Nullable:  true
     */
    private String docType;

    /**
     * 所属医馆ID
     *
     * Table:     tb_doctor
     * Column:    hos_id
     * Nullable:  true
     */
    private String hosId;

    /**
     * 所属科室ID
     *
     * Table:     tb_doctor
     * Column:    dept_id
     * Nullable:  true
     */
    private String deptId;

    /**
     * 擅长
     *
     * Table:     tb_doctor
     * Column:    expert_desc
     * Nullable:  true
     */
    private String expertDesc;

    /**
     * 预约费用
     *
     * Table:     tb_doctor
     * Column:    order_price
     * Nullable:  true
     */
    private BigDecimal orderPrice;

    /**
     * 备注
     *
     * Table:     tb_doctor
     * Column:    memo
     * Nullable:  true
     */
    private String memo;

    /**
     * 创建时间
     *
     * Table:     tb_doctor
     * Column:    created_time
     * Nullable:  true
     */
    private Date createdTime;

    /**
     * 最后修改时间
     *
     * Table:     tb_doctor
     * Column:    edited_time
     * Nullable:  true
     */
    private Date editedTime;

    /**
     * 系统状态
     *
     * Table:     tb_doctor
     * Column:    is_deleted
     * Nullable:  true
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}