package com.xzit.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: tb_doctor_task
 */
@Data
public class DoctorTask implements Serializable {
    /**
     * 主键
     *
     * Table:     tb_doctor_task
     * Column:    id
     * Nullable:  false
     */
    private String id;

    /**
     * 上班时间
     *
     * Table:     tb_doctor_task
     * Column:    start_time
     * Nullable:  false
     */
    private Date startTime;

    /**
     * 下班时间
     *
     * Table:     tb_doctor_task
     * Column:    end_time
     * Nullable:  false
     */
    private Date endTime;

    /**
     * 当天总共预约名额
     *
     * Table:     tb_doctor_task
     * Column:    total_nums
     * Nullable:  false
     */
    private String totalNums;

    /**
     * 剩余的预约名额
     *
     * Table:     tb_doctor_task
     * Column:    res_nums
     * Nullable:  false
     */
    private String resNums;

    /**
     * Table:     tb_doctor_task
     * Column:    is_deleted
     * Nullable:  true
     */
    private String isDeleted;

    /**
     * Table:     tb_doctor_task
     * Column:    creator
     * Nullable:  true
     */
    private String creator;

    /**
     * Table:     tb_doctor_task
     * Column:    editor
     * Nullable:  true
     */
    private String editor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_doctor_task
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}