package com.xzit.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: tb_hospital
 */
@Data
public class Hospital implements Serializable {
    /**
     * 医馆ID,自增
     *
     * Table:     tb_hospital
     * Column:    id
     * Nullable:  false
     */
    private String id;

    /**
     * 医馆名称
     *
     * Table:     tb_hospital
     * Column:    hos_name
     * Nullable:  true
     */
    private String hosName;

    /**
     * 详细地址
     *
     * Table:     tb_hospital
     * Column:    hos_addr
     * Nullable:  true
     */
    private String hosAddr;

    /**
     * 医师总数
     *
     * Table:     tb_hospital
     * Column:    doctor_num
     * Nullable:  true
     */
    private Integer doctorNum;

    /**
     * 科室总数
     *
     * Table:     tb_hospital
     * Column:    dept_num
     * Nullable:  true
     */
    private Integer deptNum;

    /**
     * 备注
     *
     * Table:     tb_hospital
     * Column:    memo
     * Nullable:  true
     */
    private String memo;

    /**
     * 创建时间
     *
     * Table:     tb_hospital
     * Column:    create_time
     * Nullable:  true
     */
    private Date createTime;

    /**
     * 创建人
     *
     * Table:     tb_hospital
     * Column:    creator
     * Nullable:  true
     */
    private String creator;

    /**
     * 最后修改时间
     *
     * Table:     tb_hospital
     * Column:    edited_time
     * Nullable:  true
     */
    private Date editedTime;

    /**
     * 编辑人
     *
     * Table:     tb_hospital
     * Column:    editor
     * Nullable:  true
     */
    private String editor;

    /**
     * 系统状态
     *
     * Table:     tb_hospital
     * Column:    is_deleted
     * Nullable:  true
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_hospital
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}