package com.xzit.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: tb_order_info
 */
@Data
public class OrderInfo implements Serializable {
    /**
     * ID,自增
     *
     * Table:     tb_order_info
     * Column:    id
     * Nullable:  false
     */
    private String id;

    /**
     * 预约单号
     *
     * Table:     tb_order_info
     * Column:    order_code
     * Nullable:  true
     */
    private String orderCode;

    /**
     * 预约医师ID
     *
     * Table:     tb_order_info
     * Column:    doc_id
     * Nullable:  true
     */
    private String docId;

    /**
     * 联系人ID
     *
     * Table:     tb_order_info
     * Column:    patient_id
     * Nullable:  true
     */
    private String patientId;

    /**
     * 预约类型(1-专家门诊)
     *
     * Table:     tb_order_info
     * Column:    order_type
     * Nullable:  false
     */
    private String orderType;

    /**
     * 是否支付
     *
     * Table:     tb_order_info
     * Column:    is_pay
     * Nullable:  false
     */
    private String isPay;

    /**
     * 初/复诊(1-初诊、2-复诊)
     *
     * Table:     tb_order_info
     * Column:    order_count
     * Nullable:  true
     */
    private String orderCount;

    /**
     * 备注
     *
     * Table:     tb_order_info
     * Column:    memo
     * Nullable:  true
     */
    private String memo;

    /**
     * 预约日期
     *
     * Table:     tb_order_info
     * Column:    order_date
     * Nullable:  true
     */
    private Date orderDate;

    /**
     * 就诊日期
     *
     * Table:     tb_order_info
     * Column:    treat_date
     * Nullable:  true
     */
    private Date treatDate;

    /**
     * 就诊状态(1-待就诊、2-已就诊)
     *
     * Table:     tb_order_info
     * Column:    treate_status
     * Nullable:  true
     */
    private String treateStatus;

    /**
     * 创建时间
     *
     * Table:     tb_order_info
     * Column:    create_time
     * Nullable:  true
     */
    private Date createTime;

    /**
     * 最后修改时间
     *
     * Table:     tb_order_info
     * Column:    edited_time
     * Nullable:  true
     */
    private Date editedTime;

    /**
     * 系统状态
     *
     * Table:     tb_order_info
     * Column:    is_deleted
     * Nullable:  true
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}