package com.xzit.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: tb_patient
 */
@Data
public class Patient implements Serializable {
    /**
     * ID,自增
     *
     * Table:     tb_patient
     * Column:    id
     * Nullable:  false
     */
    private String id;

    /**
     * 用户id
     *
     * Table:     tb_patient
     * Column:    user_id
     * Nullable:  false
     */
    private String userId;

    /**
     * 备注
     *
     * Table:     tb_patient
     * Column:    memo
     * Nullable:  true
     */
    private String memo;

    /**
     * 创建时间
     *
     * Table:     tb_patient
     * Column:    create_time
     * Nullable:  false
     */
    private Date createTime;

    /**
     * 最后修改时间
     *
     * Table:     tb_patient
     * Column:    edited_time
     * Nullable:  false
     */
    private Date editedTime;

    /**
     * 修改人
     *
     * Table:     tb_patient
     * Column:    editor
     * Nullable:  false
     */
    private String editor;

    /**
     * 是否被删除
     *
     * Table:     tb_patient
     * Column:    is_deleted
     * Nullable:  false
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_patient
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}