package com.xzit.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: tb_role
 */
@Data
public class Role implements Serializable {
    /**
     * 角色id
     *
     * Table:     tb_role
     * Column:    id
     * Nullable:  false
     */
    private String id;

    /**
     * 角角色名
     *
     * Table:     tb_role
     * Column:    role_name
     * Nullable:  false
     */
    private String roleName;

    /**
     * 介绍
     *
     * Table:     tb_role
     * Column:    intro
     * Nullable:  true
     */
    private String intro;

    /**
     * 创建时间
     *
     * Table:     tb_role
     * Column:    created_time
     * Nullable:  false
     */
    private Date createdTime;

    /**
     * 创建人
     *
     * Table:     tb_role
     * Column:    creator
     * Nullable:  false
     */
    private String creator;

    /**
     * 编辑时间
     *
     * Table:     tb_role
     * Column:    edited_time
     * Nullable:  false
     */
    private Date editedTime;

    /**
     * 编辑人
     *
     * Table:     tb_role
     * Column:    editor
     * Nullable:  false
     */
    private String editor;

    /**
     * 是否删除
     *
     * Table:     tb_role
     * Column:    is_deleted
     * Nullable:  false
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}