package com.xzit.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: tb_role_permission
 */
@Data
public class RolePermission implements Serializable {
    /**
     * 角色权限表id
     *
     * Table:     tb_role_permission
     * Column:    id
     * Nullable:  false
     */
    private String id;

    /**
     * Table:     tb_role_permission
     * Column:    role_id
     * Nullable:  false
     */
    private String roleId;

    /**
     * Table:     tb_role_permission
     * Column:    permission_id
     * Nullable:  false
     */
    private String permissionId;

    /**
     * Table:     tb_role_permission
     * Column:    created_time
     * Nullable:  false
     */
    private Date createdTime;

    /**
     * Table:     tb_role_permission
     * Column:    creator
     * Nullable:  false
     */
    private String creator;

    /**
     * Table:     tb_role_permission
     * Column:    edited_time
     * Nullable:  false
     */
    private Date editedTime;

    /**
     * Table:     tb_role_permission
     * Column:    editor
     * Nullable:  false
     */
    private String editor;

    /**
     * Table:     tb_role_permission
     * Column:    is_deleted
     * Nullable:  false
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_role_permission
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}