package com.xzit.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: tb_users
 */
@Data
public class User implements Serializable {
    /**
     * 用户id
     *
     * Table:     tb_users
     * Column:    id
     * Nullable:  false
     */
    private String id;

    /**
     * 用户的状态:0正常，1禁用
     *
     * Table:     tb_users
     * Column:    user_state
     * Nullable:  false
     */
    private String userState;

    /**
     * 用户名
     *
     * Table:     tb_users
     * Column:    user_name
     * Nullable:  false
     */
    private String userName;

    /**
     * 真实姓名
     *
     * Table:     tb_users
     * Column:    real_name
     * Nullable:  false
     */
    private String realName;

    /**
     * 性别0:男1女
     *
     * Table:     tb_users
     * Column:    sex
     * Nullable:  false
     */
    private String sex;

    /**
     * 年龄
     *
     * Table:     tb_users
     * Column:    age
     * Nullable:  false
     */
    private String age;

    /**
     * 头像地址
     *
     * Table:     tb_users
     * Column:    head_img_url
     * Nullable:  false
     */
    private String headImgUrl;

    /**
     * 手机号
     *
     * Table:     tb_users
     * Column:    mobile
     * Nullable:  false
     */
    private String mobile;

    /**
     * 密码
     *
     * Table:     tb_users
     * Column:    password
     * Nullable:  false
     */
    private String password;

    /**
     * 登录token
     *
     * Table:     tb_users
     * Column:    token
     * Nullable:  false
     */
    private String token;

    /**
     * 创建时间
     *
     * Table:     tb_users
     * Column:    created_time
     * Nullable:  false
     */
    private Date createdTime;

    /**
     * 修改时间
     *
     * Table:     tb_users
     * Column:    edited_time
     * Nullable:  false
     */
    private Date editedTime;

    /**
     * 是否被删除
     *
     * Table:     tb_users
     * Column:    is_deleted
     * Nullable:  false
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_users
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}