package com.xzit.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: tb_users_role
 */
@Data
public class UserRole implements Serializable {
    /**
     * 用户角色
     *
     * Table:     tb_users_role
     * Column:    id
     * Nullable:  false
     */
    private String id;

    /**
     * 用户id
     *
     * Table:     tb_users_role
     * Column:    users_id
     * Nullable:  false
     */
    private String usersId;

    /**
     * 角色id
     *
     * Table:     tb_users_role
     * Column:    role_id
     * Nullable:  false
     */
    private String roleId;

    /**
     * 创建时间
     *
     * Table:     tb_users_role
     * Column:    created_time
     * Nullable:  false
     */
    private Date createdTime;

    /**
     * 创建者
     *
     * Table:     tb_users_role
     * Column:    creator
     * Nullable:  false
     */
    private String creator;

    /**
     * 编辑时间
     *
     * Table:     tb_users_role
     * Column:    edited_time
     * Nullable:  false
     */
    private Date editedTime;

    /**
     * 编辑者
     *
     * Table:     tb_users_role
     * Column:    editor
     * Nullable:  false
     */
    private String editor;

    /**
     * 是否删除
     *
     * Table:     tb_users_role
     * Column:    is_deleted
     * Nullable:  false
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_users_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}